In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parents[0]))

from scripts.data.load_data import cargar_raw
from scripts.data.clean_data import limpiar_datos
from scripts.data.feature_engineering import preparar_df, crear_features
# Cargar datos
df = cargar_raw("titanic_dataset.csv")

# Limpiar
df_limpio = limpiar_datos(df)

# Ver features creadas
df_features = crear_features(df_limpio)
df_features.head()

# Preparar data
X, y, preprocessor = preparar_df(df_limpio)

# Transformar
X_transformed = preprocessor.fit_transform(X)

# Ver resultado final
import pandas as pd

X_final = pd.DataFrame(
    X_transformed,
    columns=preprocessor.get_feature_names_out()
)

X_final.head()

,num__Age,ordinal__Pclass,cat__Sex_female,cat__Sex_male,cat__Title_Master,cat__Title_Miss,cat__Title_Mr,cat__Title_Mrs,cat__Title_Rare,cat__Family_group_grande,cat__Family_group_pequena,cat__Family_group_solo,cat__Embarked_C,cat__Embarked_Q,cat__Embarked_S
0,22.0,3.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,38.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,26.0,3.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,35.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,35.0,3.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [3]:
X_final.shape

(891, 15)

In [4]:
X_final.columns

Index(['num__Age', 'ordinal__Pclass', 'cat__Sex_female', 'cat__Sex_male',
       'cat__Title_Master', 'cat__Title_Miss', 'cat__Title_Mr',
       'cat__Title_Mrs', 'cat__Title_Rare', 'cat__Family_group_grande',
       'cat__Family_group_pequena', 'cat__Family_group_solo',
       'cat__Embarked_C', 'cat__Embarked_Q', 'cat__Embarked_S'],
      dtype='object')

In [5]:
X_final.describe()

,num__Age,ordinal__Pclass,cat__Sex_female,cat__Sex_male,cat__Title_Master,cat__Title_Miss,cat__Title_Mr,cat__Title_Mrs,cat__Title_Rare,cat__Family_group_grande,cat__Family_group_pequena,cat__Family_group_solo,cat__Embarked_C,cat__Embarked_Q,cat__Embarked_S
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,29.361582,2.308642,0.352413,0.647587,0.044893,0.207632,0.580247,0.141414,0.025814,0.069585,0.327722,0.602694,0.188552,0.086420,0.725028
std,13.019697,0.836071,0.477990,0.477990,0.207186,0.405840,0.493796,0.348644,0.158668,0.254589,0.469646,0.489615,0.391372,0.281141,0.446751
min,0.420000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,22.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,28.000000,3.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
75%,35.000000,3.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000
max,80.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
X_final.isna().sum().sum()

0

In [7]:
X_final.dtypes.value_counts()

float64    15
Name: count, dtype: int64